(Fix) sar wind: fix spatial extent breaking seeder
aodn/geoserver-config pull request #762
Opened 2022-12-01 03:24 UTC by lbesnard

2022-12-01 03:27 UTC, lbesnard commented
https://github.com/aodn/issues/issues/1287#issuecomment-1333087601

2022-12-01 06:04 UTC, craigrose requested changes

2022-12-01 06:04 UTC, craigrose commented on workspaces/imos/JNDI_srs_surface_waves_sar_wind/srs_surface_waves_sar_wind_fv01_map/featuretype.xml
> +    <minx>-180x>
Missing `</minx>`

2022-12-01 22:22 UTC, merged

2022-12-02 03:41 UTC, ggalibert commented on workspaces/imos/JNDI_srs_surface_waves_sar_wind/srs_surface_waves_sar_wind_fv01_map/featuretype.xml
> +    <minx>-180x></minx>
typo there, should be '-180' not '-180x'